services:
  db:
    image: mysql:8.0
    container_name: auction_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auction_db
    volumes:
      - db_data:/var/lib/mysql
      - ./database/auction_db.sql:/docker-entrypoint-initdb.d/auction_db.sql:ro

  web:
    build: .
    container_name: auction_web
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html

volumes:
  db_data:
